CREATE TABLE IF NOT EXISTS PUBLIC.USERS (
	ID varchar(5) PRIMARY KEY,
	FIRST_NAME VARCHAR(30) NOT NULL,
	LAST_NAME VARCHAR(30) NOT NULL,
	BIRTHDATE date NOT NULL,
	CLASS VARCHAR(4) NULL,
	SCHOOL_EMAIL VARCHAR(35) NULL,
	PERSONAL_EMAIL VARCHAR(35) NULL,
	RFID INTEGER NULL,
	USER_TYPE INTEGER NOT NULL,
	STATUS INTEGER NOT NULL,
	LOCKER_NUMBER VARCHAR(4) NULL,
	TEMP_PASSWORD VARCHAR(20) NULL
);